name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint
      run: npm run lint
      
    - name: Run Unit Tests
      run: npm run test -- --run --reporter=verbose
      
    - name: Run Unit Tests with Coverage
      run: npm run test:coverage -- --run
      
    - name: Run E2E Tests
      run: npm run test tests/e2e/ -- --run --reporter=verbose
      
    - name: Build project
      run: npm run build
      
    - name: Generate static site
      run: npm run generate
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      if: success()
      with:
        files: ./coverage/lcov.info
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }} 